name: 'matrix'
description: 'A tool for compile-time project configuration.'
author: 'Aleks Rutins'
inputs:
  config:
    required: false
    description: "Path to your project's Matrix configuration; defaults to `matrix.toml`."
    default: 'matrix.toml'
runs:
  using: 'node18'
  main: 'dist/index.js'
